{{- if .Values.serviceAccounts.sparkoperator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-operator.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.sparkJobNamespace }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
{{- end }}
